# Generated by Django 5.0.3 on 2024-04-11 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("static_blog_app", "0003_all"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="all",
            new_name="alls",
        ),
    ]
